### PR TITLE
Raise fault

### PR DESCRIPTION
**Pull request by carloseberhardt**
This adds support for the RaiseFault policy.

### CODE REVIEW

**Comment by kevinswiber** [comment]
From the Apigee docs:

> &lt;IgnoreUnresolvedVariables&gt; element
> 
> (Optional) Ignores any unresolved variable error in the Flow. Valid values: true/false. Default true.

With the default value being `true` and `xml:",omitempty"` being set as the tag, the output for the `<IgnoreUnresolvedVariables/>` element will be omitted when the HCL is `ignored_unresolved_variables = false`.

The AssignMessage documentation doesn't say the same, and I know it uses `<IgnoreUnresolvedVariables/>`.  @carloseberhardt, do you know if the default for AssignMessage is also true?

Can you add something like this around line 62 of `config/policy/raise_fault.go`?

``` go
    if ignoreUnresolved := listVal.Filter("ignore_unresolved_variables"); len(ignoreUnresolved.Items) == 0 {
        p.IgnoreUnresolvedVariables = true
    }
```

This will check the HCL for the `ignore_unresolved_variables` key, and if it doesn't exist, it will change the value in the struct to `true`.  You'll also need to remove the `xml:",omitempty"` tag from the `IgnoreUnresolvedVariables` field in the `RaiseFaultPolicy` struct.

Otherwise, it looks good to me!

Thanks!

**Comment by carloseberhardt** [comment]
added and tested.. seems to be working

**Comment by kevinswiber** [comment]
Looks good!  I'll merge.

**Comment by kevinswiber** [comment]
Merged here: 07438f05676ab6929c8ee67410587fb31dfe39dd

**Pull request closed without merging**
